builders:
  protobufBuilder:
    import: "package:proto_builder/builder.dart"
    builder_factories: ["buildProtobuf"]
    build_extensions:
      .proto:
        - .pb.dart,
        - .pbenum.dart
        - .pbgrpc.dart
        - .pbjson.dart
    build_to: cache
    auto_apply: dependents
