name: proto_builder
description: Protobuf builder
version: 0.0.3

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  build: ^1.3.0
  protoc_plugin: ^19.0.1

dev_dependencies:
  build_runner: ^1.10.1
  build_config: ^0.4.2
  pedantic: ^1.9.0
  test: ^1.14.4
