name: proto_builder
description: >-
  "This package generate protobuf files from poroto files." "Default output path
  is './lib/protos/src/[proto_file_name]/'"

repository: "https://github.com/efa-dev/proto_builder"
version: 0.0.3

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  build: ^1.3.0
  protoc_plugin: ^19.0.1
  yaml: ^2.2.1
  glob: ^1.2.0
  logging: ^0.11.4

dev_dependencies:
  build_runner: ^1.10.1
  build_config: ^0.4.2
  pedantic: ^1.9.0
  test: ^1.14.4
